apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config
  labels:
    troubleshooting-lab/scenario: external-secret-not-syncing
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: lab-vault
    kind: SecretStore
  target:
    name: synced-app-config
  data:
    - secretKey: username
      remoteRef:
        key: /apps/demo/config
        property: username
    - secretKey: password
      remoteRef:
        key: /apps/demo/config
        property: password

