apiVersion: v1
kind: ServiceAccount
metadata:
  name: private-registry-runner
  labels:
    troubleshooting-lab/scenario: imagepullbackoff-private-registry
imagePullSecrets:
  - name: private-registry-credentials

